app: demo-app
env: dev
namespace: default
deploy:
  branch: main
  event: push
chart:
  repository: https://chart.onechart.dev
  name: onechart
  version: 0.38.0
values:
  gitRepository: wonderschool/demo-app
  gitSha: '{{ .GITHUB_SHA }}'
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt
    host: demo-app.wonderschool.dev
    tlsEnabled: true
strategicMergePatches: ""
json6902Patches: []
manifests: ""
