app: demo-app
env: staging
namespace: default
deploy:
  branch: main
  event: push
chart:
  repository: https://chart.onechart.dev
  name: onechart
  version: 0.38.0
values:
  image:
    repository: "ghcr.io/wonderschool/demo-app"
    tag: "{{ .GITHUB_SHA }}"
  imagePullSecrets:
    - name: dockerconfigjson-github-com
  containerPort: 9000
  # ingress:
  #   annotations:
  #     kubernetes.io/ingress.class: nginx
  #     cert-manager.io/cluster-issuer: letsencrypt
  #   host: demo-app.wonderschool.dev
  #   tlsEnabled: true
  ingresses:
    - host: demo-app.wonderschool.dev
      annotations:
        kubernetes.io/ingress.class: nginx
      tlsEnabled: true
    - host: demo-app.onepreschool.com
      annotations:
        kubernetes.io/ingress.class: nginx
strategicMergePatches: ""
json6902Patches: []
manifests: ""
