name: Deploy Preview App

<<<<<<< HEAD:.github/workflows/cicd.yaml
=======
on:
  pull_request:
    branches:
      - 'main'

>>>>>>> 9c94cb1 (cicd testing):.github/workflows/deploy-preview.yaml
jobs:
  deploy:
    name: Docker Build/Push/Release
    runs-on: ubuntu-latest
<<<<<<< HEAD:.github/workflows/cicd.yaml
    if: github.ref_name == 'main' || startsWith(github.ref_name, 'MP-')
=======
    if: github.event.pull_request.draft == false
>>>>>>> 9c94cb1 (cicd testing):.github/workflows/deploy-preview.yaml
    needs:
      - build
    steps:
    - name: 🛑 Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: ⬇️ Check out
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: 🐋 Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }} # `PAT` is a secret that contains your Personal Access Token with `write:packages` scope
    - name: 🐋 Build and push docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          ghcr.io/wonderschool/demo-app:${{ github.sha }}
    - name: Gimlet Artifact Shipper Action
      uses: gimlet-io/gimlet-artifact-shipper-action@v0.8.2
      env:
        GIMLET_SERVER: ${{ secrets.GIMLET_SERVER }}
        GIMLET_TOKEN: ${{ secrets.GIMLET_TOKEN }}
